In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("stock_returns.csv")
df

       year  nvidia_returns  reliance_returns
0      2016          122.14             47.43
1      2017           83.91             12.09
2      2018          -50.03            -13.63
3      2019           82.19             22.42
4      2020          125.84             62.59
5      2021           50.53             33.70
6      2022           48.57             10.26
7       NaN             NaN               NaN
8  Variance         3553.55            645.78
9   Std Dev           59.61             25.41

In [29]:
df.describe()

              year  nvidia_returns  reliance_returns
count     7.000000        7.000000          7.000000
mean   2019.000000       66.164286         24.980000
std       2.160247       59.611670         25.412166
min    2016.000000      -50.030000        -13.630000
25%    2017.500000       49.550000         11.175000
50%    2019.000000       82.190000         22.420000
75%    2020.500000      103.025000         40.565000
max    2022.000000      125.840000         62.590000

In [9]:
print('Nvidia STD = ', df.nvidia_returns.std())
print('Nvidia Var = ',df.nvidia_returns.var())

Nvidia STD =  1163.8825293924642
Nvidia Var =  1354622.5422250002

In [10]:
print('Reliance STD=',df.reliance_returns.std())
print('Reliance Var=',df.reliance_returns.var())

Reliance STD= 208.08254018003956
Reliance Var= 43298.343527777775